### ISSUE TITLE
why use sleep

### ISSUE THREAD

**Issue by vaststar** [Threesome2/team#1]
hey dude,I find some sleep-code in your program.
Here is my question: can these verify issuses be done while someone's network speed doesn't qualify your sleep time like sleep(5)?

**Comment by Threesome2** [comment]
hey silly, this is how we do.if your network doesn't work, tell your boss to change a better one.kidding.if 5 seconds not working for your network, try 10.

**Comment by Threesome2** [comment]
> hey dude,I find some sleep-code in your program.
> Here is my question: can these verify issuses be done while someone's network speed doesn't qualify your sleep time like sleep(5)?
hey silly, this is how we do.if your network doesn't work, tell your boss to change a better one.kidding.if 5 seconds not working for your network, try 10.

**Comment by Threesome2** [comment]
> hey dude,I find some sleep-code in your program.
> Here is my question: can these verify issuses be done while someone's network speed doesn't qualify your sleep time like sleep(5)?
> hey silly, this is how we do.if your network doesn't work, tell your boss to change a better one.kidding.if 5 seconds not working for your network, try 10.

still working
